@0xce3cc6ea0246fc83; # unique file ID, generated by `capnp id'

using Cxx = import "/capnp/c++.capnp";

$Cxx.namespace("neon::session");

struct SessionEvent {
    enum Command {
      createSession   @0;
      releaseSession  @1;
      shutdown        @2;
    }

    command   @0 :Command;
    name      @1 :Text;
    uuid      @2 :Text;
}